/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jd_jni_TestJni */

#ifndef _Included_com_jd_jni_TestJni
#define _Included_com_jd_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jd_jni_TestJni
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_jni_TestJni_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
